### ISSUE TITLE
add footer w/ CC-BY license

### ISSUE THREAD

**Issue by kirschbombe** [bensonhan/ideptoolkit-hyde#10]
footer will have 

`<p>&copy; {{ site.time | date: '%Y' }} UCLA Library. Licensed under a <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US">CC BY-NC-SA 3.0.</a> license.</p>`

**Comment by bensonhan** [comment]
added footer!

**Comment by kirschbombe** [comment]
I edited the footer, but cannot seem to get the positioning right. Using `position: absolute` to make it stick to the bottom of page, but that throws off the alignment.

**Comment by kirschbombe** [comment]
I moved the footer to the sidebar for now. I left the main content footer code, but commented out. #21

**Comment by kirschbombe** [comment]
I think I like it where it is. Closing this issue.
